name: Build & Deploy (SSH to cPanel)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: metal-org

    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      # Adjust if your build output folder isn't "dist"
      BUILD_DIR: dist
      # Optionally pin Node version that matches your project
      NODE_VERSION: '20'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Package build into a tarball for faster/safer upload
      - name: Create tarball
        run: |
          tar -C $BUILD_DIR -czf web_build.tar.gz .

      - name: Prepare SSH key & known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_deploy
          chmod 600 ~/.ssh/id_deploy
          ssh-keyscan -p "${SSH_PORT}" -H "${SSH_HOST}" >> ~/.ssh/known_hosts

      - name: Ensure remote path exists
        run: |
          ssh -p "${SSH_PORT}" -i ~/.ssh/id_deploy "${SSH_USER}@${SSH_HOST}" "
            mkdir -p '${DEPLOY_PATH}' &&
            echo '--- Contents of ${DEPLOY_PATH} ---' &&
            ls -la '${DEPLOY_PATH}'
          "

      # - name: Deploy with rsync (override existing files)
      #   run: |
      #     rsync -az --delete \
      #       --exclude ".htaccess" \
      #       -e "ssh -p ${SSH_PORT} -i ~/.ssh/id_deploy -o StrictHostKeyChecking=yes" \
      #       "${BUILD_DIR}/" "${SSH_USER}@${SSH_HOST}:${DEPLOY_PATH}/"

      - name: Deploy with rsync (override existing files)
        run: |
          rsync -az \
            -e "ssh -p ${SSH_PORT} -i ~/.ssh/id_deploy -o StrictHostKeyChecking=yes" \
            "${BUILD_DIR}/" "${SSH_USER}@${SSH_HOST}:${DEPLOY_PATH}/"